version: '3.8'
services:
  backend:
    build: ./Project
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/FitnessClub
      - spring.datasource.username=test
      - spring.datasource.password=test
      - PFPS_PATH=/app/pfps
      - jwt.token.secret=ofit
      - jwt.token.expired=3600000
      - jwt.refreshToken.expired=2592000000
      - SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE=10MB
      - SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE=10MB
    depends_on:
      - postgres
      - redis
  frontend:
    build:
      context: ./ProjectReact
      args:
        - REACT_APP_API_URL=http://localhost:8080
    ports:
      - 3000:3000
    depends_on:
      - backend
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: "FitnessClub"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  redis:
    image: redis:alpine

    ports:
      - 6379:6379

    environment:
        ALLOW_EMPTY_PASSWORD: "yes"
